import "./globals.css";
import NavbarMiddle from "./components/navbarMiddle";
import NavbarTop from "./components/navbarTop";
import NavbarBottom from "./components/navbarBottom";
import Footer from "./components/footerComponent/footer";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="light">
			<body className="antialiased">
				<NavbarTop />
				<NavbarMiddle />
				<NavbarBottom />
				{children}

				<Footer />
			</body>
		</html>
	);
}
